spring.application.name=day01
# ===============================
# = DATA SOURCE
# ===============================
# Set here configuration for localhost port
server.port=9001
# Set here configurations for the database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/xsis_batch342
spring.datasource.username=postgres
spring.datasource.password=muhlis43edan
# spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect (deprecated)
# spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults= false (deprecated)
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access = true
spring.jpa.properties.hibernate.default_schema= master
# spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.hibernate.ddl-auto=update